apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-{{ .Release.Namespace }}-clusterip
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    dev: {{ .Values.name }}
