apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      dev: {{ .Values.name }}
  template:
    metadata:
      labels:
        dev: {{ .Values.name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-secrets-{{ .Release.Namespace }}
                  key: DATABASE_URL
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-secrets-{{ .Release.Namespace }}
                  key: GEMINI_API_KEY
            - name: GEMINI_MODEL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-secrets-{{ .Release.Namespace }}
                  key: GEMINI_MODEL
            - name: MICROSOFT_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-secrets-{{ .Release.Namespace }}
                  key: MICROSOFT_CLIENT_ID
            - name: MICROSOFT_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-secrets-{{ .Release.Namespace }}
                  key: MICROSOFT_TENANT_ID
            - name: MICROSOFT_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-secrets-{{ .Release.Namespace }}
                  key: MICROSOFT_CLIENT_SECRET
            - name: MICROSOFT_REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-secrets-{{ .Release.Namespace }}
                  key: MICROSOFT_REDIRECT_URI
            - name: MICROSOFT_AUTHORITY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-secrets-{{ .Release.Namespace }}
                  key: MICROSOFT_AUTHORITY
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-secrets-{{ .Release.Namespace }}
                  key: JWT_SECRET_KEY
            - name: JWT_ALGORITHM
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-secrets-{{ .Release.Namespace }}
                  key: JWT_ALGORITHM
            - name: JWT_EXPIRATION_MINUTES
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-secrets-{{ .Release.Namespace }}
                  key: JWT_EXPIRATION_MINUTES
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-secrets-{{ .Release.Namespace }}
                  key: OPENAI_API_KEY
            - name: OPENAI_EMBEDDING_MODEL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-secrets-{{ .Release.Namespace }}
                  key: OPENAI_EMBEDDING_MODEL
            - name: QDRANT_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-secrets-{{ .Release.Namespace }}
                  key: QDRANT_HOST
            - name: QDRANT_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-secrets-{{ .Release.Namespace }}
                  key: QDRANT_PORT
            - name: QDRANT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-secrets-{{ .Release.Namespace }}
                  key: QDRANT_API_KEY
            - name: QDRANT_COLLECTION_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-secrets-{{ .Release.Namespace }}
                  key: QDRANT_COLLECTION_NAME
            - name: QDRANT_STORAGE_PATH
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-secrets-{{ .Release.Namespace }}
                  key: QDRANT_STORAGE_PATH
            - name: CHUNK_SIZE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-secrets-{{ .Release.Namespace }}
                  key: CHUNK_SIZE
            - name: CHUNK_OVERLAP
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-secrets-{{ .Release.Namespace }}
                  key: CHUNK_OVERLAP
            - name: UPLOAD_DIR
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-secrets-{{ .Release.Namespace }}
                  key: UPLOAD_DIR
            - name: FRONTEND_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-secrets-{{ .Release.Namespace }}
                  key: FRONTEND_URL
            - name: LITE_LLM_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-secrets-{{ .Release.Namespace }}
                  key: LITE_LLM_BASE_URL
            - name: LITE_LLM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-secrets-{{ .Release.Namespace }}
                  key: LITE_LLM_API_KEY
            - name: LITE_LLM_MODEL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-secrets-{{ .Release.Namespace }}
                  key: LITE_LLM_MODEL
          {{- if .Values.Resources.enabled }}    
          resources:
            {{- toYaml .Values.Resources.resources | nindent 12 }}
          {{- end }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30