version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: postgres-chatbot
    environment:
      POSTGRES_USER: chatbot
      POSTGRES_PASSWORD: 47billion
      POSTGRES_DB: chatbotdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:v1.16.0
    container_name: qdrant-chatbot
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

volumes:
  postgres_data:
  qdrant_data:
