"""updated column name in tables for access

Revision ID: 425ada438426
Revises: 3de7bb37b1de
Create Date: 2025-12-25 23:44:16.063988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '425ada438426'
down_revision: Union[str, Sequence[str], None] = '3de7bb37b1de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbot_access', sa.Column('created_by', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('chatbot_access_employee_id_fkey'), 'chatbot_access', type_='foreignkey')
    op.create_foreign_key(None, 'chatbot_access', 'employees', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_column('chatbot_access', 'employee_id')
    op.add_column('chatbot_permissions', sa.Column('can_review_users', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('chatbot_permissions', sa.Column('reviewer_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('chatbot_permissions_created_by_fkey'), 'chatbot_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'chatbot_permissions', 'employees', ['reviewer_id'], ['id'], ondelete='SET NULL')
    op.drop_column('chatbot_permissions', 'employee_id')
    op.drop_column('chatbot_permissions', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbot_permissions', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('chatbot_permissions', sa.Column('employee_id', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chatbot_permissions', type_='foreignkey')
    op.create_foreign_key(op.f('chatbot_permissions_created_by_fkey'), 'chatbot_permissions', 'employees', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_column('chatbot_permissions', 'reviewer_id')
    op.drop_column('chatbot_permissions', 'can_review_users')
    op.add_column('chatbot_access', sa.Column('employee_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chatbot_access', type_='foreignkey')
    op.create_foreign_key(op.f('chatbot_access_employee_id_fkey'), 'chatbot_access', 'employees', ['employee_id'], ['id'], ondelete='SET NULL')
    op.drop_column('chatbot_access', 'created_by')
    # ### end Alembic commands ###
