"""added employee email

Revision ID: aa654c568839
Revises: 398d1a51e4cb
Create Date: 2025-12-12 17:33:01.701673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa654c568839'
down_revision: Union[str, Sequence[str], None] = '398d1a51e4cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('employee_email', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'employees', ['employee_email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='unique')
    op.drop_column('employees', 'employee_email')
    # ### end Alembic commands ###
