"""updated answers table

Revision ID: d08f68d81bec
Revises: 74db83786c64
Create Date: 2025-12-15 19:44:18.742980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd08f68d81bec'
down_revision: Union[str, Sequence[str], None] = '74db83786c64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('attempter_by_id', sa.UUID(), nullable=True))
    op.add_column('answers', sa.Column('chat_history', sa.Text(), nullable=True))
    op.alter_column('answers', 'answer_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)

    # Drop indexes only if they exist (they may not exist on fresh databases
    # since the initial migration didn't create them)
    conn = op.get_bind()
    for idx_name in [
        'idx_answers_attempter_id',
        'idx_answers_question_id',
        'idx_answers_session_id',
        'idx_answers_source_type',
    ]:
        result = conn.execute(sa.text(
            "SELECT 1 FROM pg_indexes WHERE indexname = :name"
        ), {"name": idx_name})
        if result.fetchone():
            op.drop_index(op.f(idx_name), table_name='answers')

    # Drop constraints only if they exist
    for constraint_name in ['answers_attempter_id_fkey', 'fk_answers_question_id']:
        result = conn.execute(sa.text(
            "SELECT 1 FROM information_schema.table_constraints "
            "WHERE constraint_name = :name AND table_name = 'answers'"
        ), {"name": constraint_name})
        if result.fetchone():
            op.drop_constraint(op.f(constraint_name), 'answers', type_='foreignkey')

    op.create_foreign_key(None, 'answers', 'employees', ['attempter_by_id'], ['id'], ondelete='SET NULL')

    # Drop columns only if they exist
    existing_cols = {row[0] for row in conn.execute(sa.text(
        "SELECT column_name FROM information_schema.columns "
        "WHERE table_name = 'answers'"
    ))}
    for col in ['answer_content', 'attempter_id', 'attempter_name',
                'question_id', 'question_snapshot', 'source_type', 'session_id']:
        if col in existing_cols:
            op.drop_column('answers', col)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('answers', sa.Column('source_type', sa.VARCHAR(), server_default=sa.text("'quiz'::character varying"), autoincrement=False, nullable=True))
    op.add_column('answers', sa.Column('question_snapshot', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('answers', sa.Column('question_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('answers', sa.Column('attempter_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('answers', sa.Column('attempter_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('answers', sa.Column('answer_content', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.create_foreign_key(op.f('fk_answers_question_id'), 'answers', 'questions', ['question_id'], ['question_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('answers_attempter_id_fkey'), 'answers', 'employees', ['attempter_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('idx_answers_source_type'), 'answers', ['source_type'], unique=False)
    op.create_index(op.f('idx_answers_session_id'), 'answers', ['session_id'], unique=False)
    op.create_index(op.f('idx_answers_question_id'), 'answers', ['question_id'], unique=False)
    op.create_index(op.f('idx_answers_attempter_id'), 'answers', ['attempter_id'], unique=False)
    op.alter_column('answers', 'answer_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('answers', 'chat_history')
    op.drop_column('answers', 'attempter_by_id')
    # ### end Alembic commands ###
