"""updated generated by to uuid

Revision ID: fbb9031b5259
Revises: aa654c568839
Create Date: 2025-12-13 02:02:28.020862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fbb9031b5259'
down_revision: Union[str, Sequence[str], None] = 'aa654c568839'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbots', sa.Column('pdf_names', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('chatbots', 'generated_by',postgresql_using='generated_by::uuid', 
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.create_foreign_key(None, 'chatbots', 'employees', ['generated_by'], ['id'])
    op.drop_column('chatbots', 'pdf_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbots', sa.Column('pdf_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chatbots', type_='foreignkey')
    op.alter_column('chatbots', 'generated_by',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('chatbots', 'pdf_names')
    # ### end Alembic commands ###
